/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import form.form_kasir;
import form.form_user;
import form.form_persediaan_barang;
import form.form_supplier;
import form.form_menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import menu.MenuItem;

/**
 *
 * @author Asus
 */
public class mainkasir extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public mainkasir() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        excute();
    }
    private void excute(){
        //create icon
        ImageIcon iconMenu= new ImageIcon(getClass().getResource("/menu/burger.png"));
        ImageIcon iconKasir= new ImageIcon(getClass().getResource("/menu/Monitor.png"));
        ImageIcon iconStok= new ImageIcon(getClass().getResource("/menu/box.png"));
        ImageIcon iconSupplier= new ImageIcon(getClass().getResource("/menu/supplier.png"));
        ImageIcon iconSubMenu= new ImageIcon(getClass().getResource("/menu/next.png"));
        
        //create submenu
        MenuItem menuMenu=new MenuItem(iconMenu,"Data Menu",new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
           panelbody.removeAll();
           panelbody.add(new form_menu());
           panelbody.repaint();
           panelbody.revalidate();
            }
        });
        
        MenuItem menuSupplier=new MenuItem(iconSupplier,"Data Supplier",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
           panelbody.removeAll();
           panelbody.add(new form_supplier());
           panelbody.repaint();
           panelbody.revalidate();
            }      
        });
        
        
        MenuItem menuBarangBaru=new MenuItem(iconSubMenu,"Barang Baru",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
           panelbody.removeAll();
           panelbody.add(new form_persediaan_barang());
           panelbody.repaint();
           panelbody.revalidate();
            }      
        });
        
        MenuItem menuStokMasuk=new MenuItem(iconSubMenu,"Pembelian Barang",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
           panelbody.removeAll();
           
           panelbody.repaint();
           panelbody.revalidate();
            }      
        });
        

        //Menu Utama
        MenuItem menuStok= new MenuItem(iconStok,"Persediaan Barang",null,menuBarangBaru,menuStokMasuk);
        
        
        MenuItem menuKasir= new MenuItem(iconKasir,"Kasir",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
            panelbody.removeAll();
            panelbody.add(new form_kasir());
            panelbody.repaint();
            panelbody.revalidate();
            }
        });
        
        
        addMenu( menuMenu, menuSupplier, menuStok, menuKasir);
    }
    
    private void addMenu(MenuItem... menu){
        for(int i=0;i<menu.length;i++){
            menus.add(menu[i]);
            ArrayList<MenuItem>subMenu=menu[i].getSubMenu();
            for(MenuItem m:subMenu){
                addMenu(m);
            }
        
    }
        menus.repaint();
        menus.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelheader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menus = new keeptoo.KGradientPanel();
        panelbody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelheader.setBackground(new java.awt.Color(255, 153, 51));
        panelheader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelheader.setMinimumSize(new java.awt.Dimension(100, 70));
        panelheader.setPreferredSize(new java.awt.Dimension(988, 75));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GOVERNOR BURGER");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("G O V E R N O R B U R G E R");

        getContentPane().add(panelheader, java.awt.BorderLayout.PAGE_START);

        panelmenu.setBackground(new java.awt.Color(255, 255, 255));
        panelmenu.setMinimumSize(new java.awt.Dimension(250, 100));
        panelmenu.setPreferredSize(new java.awt.Dimension(250, 100));
        panelmenu.setLayout(new java.awt.BorderLayout());

        menus.setkEndColor(new java.awt.Color(255, 153, 0));
        menus.setkGradientFocus(600);
        menus.setkStartColor(new java.awt.Color(255, 204, 204));
        menus.setLayout(new javax.swing.BoxLayout(menus, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menus);

        panelmenu.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelmenu, java.awt.BorderLayout.LINE_START);

        panelbody.setBackground(new java.awt.Color(255, 255, 255));
        panelbody.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelbody, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1004, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainkasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel menus;
    private javax.swing.JPanel panelbody;
    private javax.swing.JPanel panelheader;
    private javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables
}
